# Build Stage
FROM maven:3.9.6-eclipse-temurin-17-alpine as build
WORKDIR /app
COPY backend/ /app
RUN mvn clean install -DskipTests

# Run Stage
FROM openjdk:23-slim as run
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8443

ENTRYPOINT ["java", "-jar", "app.jar"]